# Generated by Django 4.2.1 on 2023-05-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=255, unique=True)),
                ("author", models.CharField(max_length=100)),
                ("pub_date", models.DateTimeField()),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        max_length=255, upload_to="images/products/books"
                    ),
                ),
                ("genre", models.CharField(max_length=200)),
                ("availability", models.CharField(max_length=15)),
                ("price", models.CharField(max_length=10)),
            ],
        ),
    ]
