# Generated by Django 4.2.1 on 2023-05-05 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_model", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="product_id",
        ),
    ]
