# Generated by Django 4.2.1 on 2023-05-07 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("order_model", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="category",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_id",
            field=models.CharField(max_length=20),
        ),
    ]
