# Generated by Django 4.2.1 on 2023-05-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clothes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=100)),
                ("size", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="images/clothes")),
                ("categories", models.CharField(max_length=200)),
                ("availability", models.CharField(max_length=15)),
                ("price", models.CharField(max_length=10)),
            ],
        ),
    ]
