# Generated by Django 4.2.1 on 2023-05-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_code", models.CharField(max_length=3)),
                ("bank_tran_no", models.CharField(max_length=20)),
                ("ip", models.CharField(max_length=20)),
                ("order_info", models.CharField(max_length=255)),
                ("pay_date", models.DateTimeField()),
                ("pay_tran_no", models.CharField(max_length=20)),
                ("pay_tran_status", models.CharField(max_length=2)),
                ("order_id", models.CharField(max_length=20)),
                ("card_type", models.CharField(max_length=20)),
            ],
        ),
    ]
